name: 'submodule updates'

on: 
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'dustyspace/example-voting-submodules'
      CHECKOUT_BRANCH: 'releasehub-integration'
      PR_AGAINST_BRNACH: 'releasehub-integration'
      OWNER: 'dustyspace'
    steps:
    - uses: actions/checkout@v2
    - name: run action
      id: run_action
      uses: ./
      with: 
        github_token: ${{ secrets.RELEASE_HUB_SECRET }}
        parent_repository: ${{ env.PARENT_REPOSITORY }}
        checkout_branch: ${{ env.CHECKOUT_BRANCH}}
        pr_against_branch: ${{ env.PR_AGAINST_BRNACH }}
        owner: ${{ env.OWNER }}
